### ISSUE TITLE
Layout con UserProfileLayout

### ISSUE THREAD

**Issue by JoseJuan81** [JoseJuan81/PlanificApp#3]
**Descripción**
Actividades para maquetar layout de:
- Listado de actividades (TreeList)
- Listado de Gastos
- Gannt

**Issues**
- [x] #4 Instalar componente `UserProfileLayout`
- [x] #6 Implementrar componente `UserProfileLayout`
- [x] #8 Versión móvil
- [x] #10 Pruebas con cypress
